services:
  mkdocs:
    container_name: mkdocs
    build:
      context: ..
      dockerfile: docker-compose/docker/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      LIVE_RELOAD_SUPPORT: 'true'
      FAST_MODE: 'true'
      DOCS_DIRECTORY: 'docs'
    volumes:
      - ../:/mkdocs
    working_dir: /mkdocs
    command: serve --dev-addr=0.0.0.0:8000
